#!/usr/bin/env python3
from __future__ import annotations

"""Generate packaged profiles and thin Agent Skill entry points.

This is a maintainer tool.  Runtime `gjb438c init` reads the generated YAML and
therefore does not need the repository-level DOCX template bundle.
"""

import argparse
from copy import deepcopy
from hashlib import sha256
from pathlib import Path
import sys
from typing import Any

import yaml

SKILL_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = SKILL_ROOT.parents[1]
if str(SKILL_ROOT) not in sys.path:
    sys.path.insert(0, str(SKILL_ROOT))

from gjb438c_suite.markdown_doc import extract_template_outline  # noqa: E402
from gjb438c_suite.profile_catalog import profile_spec  # noqa: E402
from gjb438c_suite.registry import iter_document_types, resolve_template  # noqa: E402

PROFILE_ROOT = SKILL_ROOT / "gjb438c_suite" / "data" / "profiles"


def _profile_payload(item) -> dict[str, Any]:
    template = resolve_template(item)
    outline = extract_template_outline(template)
    payload = profile_spec(item.code)
    payload.update(
        {
            "document_number": item.number,
            "document_name": item.chinese_name,
            "clause": item.clause,
            "appendix": item.appendix,
            "template_source": item.template_filename,
            "template_sha256": sha256(template.read_bytes()).hexdigest(),
            "outline": [
                {
                    "level": heading.level,
                    "title": heading.title,
                    **({"number": heading.number} if heading.number else {}),
                }
                for heading in outline
            ],
        }
    )
    return payload


def _profile_text(payload: dict[str, Any]) -> str:
    header = (
        "# Generated by tools/generate_profiles.py.\n"
        "# The outline is extracted from the repository template; quality and volume\n"
        "# rules are repository policy and are not quoted as standard clauses.\n"
    )
    return header + yaml.safe_dump(payload, allow_unicode=True, sort_keys=False, width=120)


def _thin_skill_text(item, payload: dict[str, Any]) -> str:
    required = ", ".join(payload.get("baselines", {}).get("required", [])) or "无固定必选基线"
    required_any = ", ".join(payload.get("baselines", {}).get("required_any", []))
    sources = "、".join(payload["source_materials"])
    baseline_note = f"；至少提供其一：{required_any}" if required_any else ""
    return f'''---
name: gjb438c-{item.code.lower()}
description: 当用户明确要求按 GJB 438C-2021 编制、修订、审核或导出 {item.chinese_name}（{item.code}、{item.clause}、附录{item.appendix}）时使用。该入口调用共享核心 gjb438c-md-first，并固定 document.type={item.code}；Markdown 是评审基线，DOCX 是发布物。
---

# {item.code} · {item.chinese_name}

这是 `gjb438c-md-first` 的薄路由入口，不复制渲染器、审计器或模板。

## 固定调用

```bash
gjb438c init --type {item.code} --project <project.yaml> --output docs/{item.code}.md
gjb438c audit docs/{item.code}.md --profile review
gjb438c render docs/{item.code}.md --output dist/{item.code}.docx --profile release --refresh-toc
gjb438c audit-docx dist/{item.code}.docx --profile release
gjb438c audit-volume dist/{item.code}.docx --type {item.code} --tier large
```

## 编写目标

{payload['purpose']}

## 首要来源材料

{sources}。

## 基线关系

固定必选：{required}{baseline_note}。实际剪裁必须记录理由，不得用页数或套话替代缺失证据。

## 发布原则

- 默认使用 `large` 规模档位；`prototype` 仅用于冒烟，禁止作为正式交付。
- 页数只是防止空壳的下限之一；还必须通过条目数量、来源、追踪、正文密度、薄页率和重复页率检查。
- 不得编造项目事实、测试结果、接口、性能、兼容性或签字信息。
- 详细字段合同和章节结构读取共享核心内置 Profile：`gjb438c_suite/data/profiles/{item.code.lower()}.yaml`。
'''


def _expected_files() -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for item in iter_document_types():
        payload = _profile_payload(item)
        outputs[PROFILE_ROOT / f"{item.code.lower()}.yaml"] = _profile_text(payload)
        skill = REPOSITORY_ROOT / "skills" / f"gjb438c-{item.code.lower()}" / "SKILL.md"
        outputs[skill] = _thin_skill_text(item, payload)
    return outputs


def generate(*, check: bool) -> int:
    expected = _expected_files()
    errors: list[str] = []
    expected_paths = set(expected)
    managed_paths = set(PROFILE_ROOT.glob("*.yaml"))
    managed_paths.update(REPOSITORY_ROOT.glob("skills/gjb438c-*/SKILL.md"))
    # Keep the shared core SKILL.md out of the thin-entry cleanup set.
    managed_paths.discard(SKILL_ROOT / "SKILL.md")

    for path in sorted(managed_paths - expected_paths):
        if check:
            errors.append(f"unexpected generated file: {path.relative_to(REPOSITORY_ROOT)}")
        else:
            path.unlink()
            try:
                path.parent.rmdir()
            except OSError:
                pass

    for path, content in expected.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        if check:
            errors.append(f"out of date: {path.relative_to(REPOSITORY_ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 2
    print(f"profiles=20 thin_skills=20 mode={'check' if check else 'write'}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
